plugins {
    id 'java'
    id 'java-library'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

dependencies {
    api(project(":dinky-common"))
}
//jar {
//    archiveFileName = project.name + "-" + version + '.jar'
//    buildDir(rootProject.getLayout().buildDirectory)
//    destinationDirectory=rootProject.getLayout().buildDirectory.dir("plugins/executor")
//}

test {
    useJUnitPlatform()
}
