plugins {
    id 'java'
    id 'java-library'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

dependencies {
    implementation(platform(libs.spring.boot.dependencies))
    implementation(platform(libs.mybatis.plus.bom))

    compileOnlyApi(libs.lombok)
    annotationProcessor(libs.lombok)

    implementation(libs.mysql.connector.j)
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation('org.springframework.boot:spring-boot-starter-validation')

    implementation 'com.alibaba:druid-spring-boot-3-starter:1.2.27'
    implementation("com.baomidou:mybatis-plus-spring-boot3-starter")
    implementation("com.baomidou:mybatis-plus-jsqlparser")
    implementation 'com.github.xingfudeshi:knife4j-openapi3-jakarta-spring-boot-starter:4.6.0'
    implementation 'cn.dev33:sa-token-spring-boot3-starter:1.44.0'
    implementation 'com.google.guava:guava:32.0.1-jre'
    implementation 'com.h2database:h2:2.3.232'
    implementation(libs.hutool.all)
    implementation(libs.fastjson2.extension.spring6)
//    implementation(project(":dinky-common"))
    implementation(project(":dinky-executor"))

    compileOnlyApi(libs.slf4j.api)
    compileOnlyApi(libs.logback.classic)
}

test {
    useJUnitPlatform()
}
